topicGroup:
  - OKB-USDT-Perp@Trades
  - OKT-USDT-Perp@Trades
  - OKB-USDT-Perp@Tickers
  - OKT-USDT-Perp@Tickers
  - OKB-USDT-Perp@Candle@detail
  - OKT-USDT-Perp@Candle@detail
  - OKB-USDT-Perp@Books@400
  - OKT-USDT-Perp@Books@400
