stgEngChannel: "WEBSRV@StgEngChannel@Trade"

webSrvTaskDispatcherParam: moduleName=WebSrvTaskDispatcherParam;taskRandAssignedThreadPoolSize=0;taskSpecificThreadPoolSize=1

dbEngParam: svcName=dbEng; dbName=BetterQuant; host=0.0.0.0; port=3306; username=root; password=showmethemoney
dbTaskDispatcherParam: moduleName=dbTaskDispatcher

tdEngParam: host=0.0.0.0; port=0; db=; username=root; password=taosdata; connPoolSize=1
maxNumOfRecReturned: 10000

logger: 
  queueSize: 128
  backingThreadsCount: 1
  defaultLoggerName: defaultLogger
  loggerGroup: 
    - 
      loggerName: "defaultLogger"
      maxFiles: 10
      maxSize: 104857600
      outputDir: "data/logs/bqweb-srv"
      outputFilename: "bqweb-srv"
      rotatingSinkPattern: "[%Y%m%d %T.%f] [%L] [%t] [%s:%#] %v"
      stdoutSinkPattern: "[%Y%m%d %T.%f] [%^%L%$] [%t] [%s:%#] %v"
