
  bqtd-market_code-symbol_type-acct_id:
      image: bqtd-market_code:${TAG}
      container_name: bqtd-market_code-symbol_type-acct_id
      build:
        context: ./bqtd-market_code
        dockerfile: ../../bqtd/bqtd-market_code/docker/Dockerfile
      volumes:
        - $ROOT_DIR_OF_INSTALLATION/betterquant/data:/usr/bin/data
        - $ROOT_DIR_OF_INSTALLATION/betterquant/config:/usr/bin/config
        - /dev:/dev
        - /tmp:/tmp
      restart: always
      stop_signal: SIGINT
      networks:
        - bqnet
      depends_on: 
        roudi:
          condition: service_healthy
        mysql:
          condition: service_healthy
      command: ['bqtd-market_code', '--conf=config/bqtd-market_code/symbol_type/bqtd-market_code-acct_id.yaml']
