topicGroup:
  - BTC-USDT@Trades
  - BTC-USDT@Tickers
  - BTC-USDT@Candle
  - BTC-USDT@Books@400
  - ETH-USDT@Trades
  - ETH-USDT@Tickers
  - ETH-USDT@Candle
  - ETH-USDT@Books@400
  - SOL-USDT@Trades
  - SOL-USDT@Tickers
  - SOL-USDT@Candle
  - BNB-USDT@Trades
  - BNB-USDT@Tickers
  - BNB-USDT@Candle
  - BNB-USDT@Books@400
  - DOGE-USDT@Trades
  - DOGE-USDT@Tickers
  - DOGE-USDT@Candle
  - DOGE-USDT@Books@400
  - DOT-USDT@Trades
  - DOT-USDT@Tickers
  - DOT-USDT@Candle
  - DOT-USDT@Books@400
  - ADA-USDT@Trades
  - ADA-USDT@Tickers
  - ADA-USDT@Candle
  - ADA-USDT@Books@400
