topicGroup:
  - 'OKB-USDT@Trades'
  - 'OKT-USDT@Trades'
  - 'OKB-USDT@Tickers'
  - 'OKT-USDT@Tickers'
  - 'OKB-USDT@Candle@detail'
  - 'OKT-USDT@Candle@detail'
  - 'OKB-USDT@Books@400'
  - 'OKT-USDT@Books@400'
