loggerConfFilename: config/BQTDBinance/cfutures/Logger.BQTDBinance.properties

marketCode: BINANCE
symbolType: CFUTURES
acctId: 10013

tdFrontParam: svcName=TD@BINANCE@SPOT; srvAddr=tcp://0.0.0.0:62000
tdFrontTaskDispatcherParam: moduleName=tdFrontTaskDispatcher; taskRandAllocThreadPoolSize=0; taskSpecificThreadPoolSize=2

addrOfWS: "wss://dstream.binance.com/ws" 
addrOfHttp: "https://dapi.binance.com"

recvWindow: 60000

secIntervalOfExtendConnLifecycle: 600
secIntervalOfSyncAssetsSnapshot: 10
secIntervalOfSyncUnclosedOrderInfo: 55
secIntervalOfReloadExternalStatusCode: 10

timeoutOfGetListenKey: 60000
timeoutOfQueryAssetInfoGroup: 60000
timeoutOfQueryOrderInfo: 60000

wsParam: svcName=WSCli; intervalOfSendPingAndCheckConn=5000; sendPing=1; expireTimeOfConn=10800000
wsTaskDispatcherParam: moduleName=wsCliTaskDispatcher; taskRandAllocThreadPoolSize=0; taskSpecificThreadPoolSize=1

dbEngParam: svcName=dbEng; dbName=BetterQuant; host=0.0.0.0; port=3306; username=root; password=123456
dbTaskDispatcherParam: moduleName=dbTaskDispatcher

intervalOfTBLMonitorOfSymbolInfo: 10000

flowCtrlRule:
  - taskGroup:  # each key
    - {name: order, weight: 1}
    - {name: cancelOrder, weight: 1}
    timeDur: 10000
    limitNum: 40
  - taskGroup:  # each ip
    - {name: extendConnLifecycle, weight: 1}
    - {name: syncAssetsSnapshot, weight: 10}
    - {name: syncUnclosedOrderInfo, weight: 1}
    timeDur: 60000
    limitNum: 200
