topicGroup:
  - {name: BTC-USDT-ThisQuarter@Trades, saveToDisk: true}
  - {name: ETH-USDT-ThisQuarter@Trades, saveToDisk: true}
  - {name: BTC-USDT-ThisQuarter@Tickers, saveToDisk: true}
  - {name: ETH-USDT-ThisQuarter@Tickers, saveToDisk: true}
  - {name: BTC-USDT-ThisQuarter@Candle@detail, saveToDisk: true}
  - {name: ETH-USDT-ThisQuarter@Candle@detail, saveToDisk: true}
  - {name: BTC-USDT-ThisQuarter@Books@400, saveToDisk: true}
  - {name: ETH-USDT-ThisQuarter@Books@400, saveToDisk: true}
