acctId: 10000

api:
  clientId: 1
  apiName: XTP
  traderServerIP: 122.112.139.0
  traderServerPort: 6102
  traderUsername: 253191001650
  traderPassword: 43uw2Zpe
  softwareKey: b8aa7173bba3470e390d787219b2112e
  localIP:

  loggerPath: data/logs/bqtd/bqtd-xtp/
  secIntervalOfHeartBeat: 15
  secIntervalOfReconnect: 10

simedMode:
  feeCurrency: CNY
  feeRatioOfTaker: 0.003
  feeRatioOfMaker: 0.002
  milliSecIntervalOfSimOrderStatus: 0

pathOfClientId2OrderId: data/TD/bqtd/bqtd-xtp

rawTDHandlerParam: moduleName=rawTDHandler; numOfUnprocessedTaskAlert=1000; taskRandAllocThreadPoolSize=0; taskSpecificThreadPoolSize=2

tdSrvChannel: "TD@TDGWChannel@Trade"
tdSrvTaskDispatcherParam: moduleName=tdSrvTaskDispatcher; taskRandAllocThreadPoolSize=0; taskSpecificThreadPoolSize=2

riskMgrChannel: "RISK@TDGWChannel@Trade"

secIntervalOfSyncAssetsSnapshot: 60
secIntervalOfSyncUnclosedOrderInfo: 30
secIntervalOfReloadExternalStatusCode: 10
secIntervalOfSaveClientId2OrderId: 10
secIntervalOfReloadFeeInfo: 10

milliSecIntervalOfSyncTask: 5

secAgoTheOrderNeedToBeSynced: 30

dbEngParam: svcName=dbEng; dbName=BetterQuant; host=0.0.0.0; port=3306; username=root; password=showmethemoney
dbTaskDispatcherParam: moduleName=dbTaskDispatcher

flowCtrlRule:
  - taskGroup:  # each key
    - {name: order, weight: 1}
    - {name: cancelOrder, weight: 1}
    timeDur: 10000
    limitNum: 40
  - taskGroup:  # each ip
    - {name: extendConnLifecycle, weight: 1}
    - {name: syncAssetsSnapshot, weight: 10}
    - {name: syncUnclosedOrderInfo, weight: 2}
    timeDur: 60000
    limitNum: 200

logger: 
  queueSize: 128
  backingThreadsCount: 1
  defaultLoggerName: defaultLogger
  loggerGroup: 
    - 
      loggerName: "defaultLogger"
      maxFiles: 10
      maxSize: 104857600
      outputDir: "data/logs/bqtd/bqtd-xtp"
      outputFilename: "bqtd-xtp"
      rotatingSinkPattern: "[%Y%m%d %T.%f] [%L] [%t] [%s:%#] %v"
      stdoutSinkPattern: "[%Y%m%d %T.%f] [%^%L%$] [%t] [%s:%#] %v"
