stgEngChannelOfTDSrv: "TD@StgEngChannel@Trade"
stgEngChannelOfRiskMgr: "RISK@StgEngChannel@Trade"
stgEngChannelOfWebSrv: "WEBSRV@StgEngChannel@Trade"

stgId: 10000

dbEngParam: svcName=dbEng; dbName=BetterQuant; host=0.0.0.0; port=3306; username=root; password=showmethemoney
dbTaskDispatcherParam: moduleName=dbTaskDispatcher

webSrv: localhost

stgInstTaskDispatcherParam: moduleName=StgInstTaskDispatcher;taskRandAssignedThreadPoolSize=0;taskSpecificThreadPoolSize=4

milliSecIntervalOfTBLMonitorOfSymbolInfo: 10000
milliSecIntervalOfTBLMonitorOfStgInstInfo: 10000

milliSecIntervalOfSyncTask: 5

timeoutOfQueryHisMD: 60000

rootDirOfStgPrivateData: /dev/shm

logger: 
  queueSize: 128
  backingThreadsCount: 1
  defaultLoggerName: defaultLogger
  loggerGroup: 
    - 
      loggerName: "defaultLogger"
      maxFiles: 10
      maxSize: 104857600
      outputDir: "data/logs/bqstg/bqstg-10000"
      outputFilename: "bqstg-10000"
      rotatingSinkPattern: "[%Y%m%d %T.%f] [%L] [%t] [%s:%#] %v"
      stdoutSinkPattern: "[%Y%m%d %T.%f] [%^%L%$] [%t] [%s:%#] %v"
